### ISSUE TITLE
model weights in gz format. 

### ISSUE THREAD

**Issue by MingchenChen93** [Rappsilber-Laboratory/AlphaLink2#1]
Hi, the model weights deposited on Zendo is in gz format. When I unzip it, we found a folder containing many files. I am wondering if this is the right model weights? Or can you elaborate on how to utilize the weights? Thanks

**Comment by nimrod-bio** [comment]
@MingchenChen93 what was the solution?
I'm in the same situation
I tried just passing the unzipped path, but got 
```
AlphaLink-Multimer_SDA_v2.pt: Is a directory
```

**Comment by lhatsk** [comment]
How did you unzip? Simply with gunzip?

**Comment by nimrod-bio** [comment]
@lhatsk it was a windows/linux incompatibility
when I ran all the commands on linux only everything was fine
sorry for the late response
