### ISSUE TITLE
Question about model confidence parameters when generating more than 1 model

### ISSUE THREAD

**Issue by andreadiianni** [Rappsilber-Laboratory/AlphaLink2#16]
To whom it may concern,
firstly many thanks for releasing this interesting tool. I would like to know how it is possible to recover interface predicted template modeling score (ipTM) when more than 1 model (e.g. 3 best models) are generated. The second question is about model ranking. What is the scoring rationale behind? In other words, when generating more than 1 model, the tool generates three models (97923, 44732 and 99982). I think the three models have been generated with different weights, and information about predicted template modeling score (pTM) of the three models can be retrieved from the notebook. I noticed that not always the model that has the highest pTM is the one that is ranked as top 1 pose (but it is fine because pTM contributes 20% to the model confidence). Then I guess the model scoring is driven by ipTM. It is correct or not? Should it be added some additional script from the colab notebook in order to recover these values when more than 1 model is generated?
Many thanks again.

**Comment by lhatsk** [comment]
97923, 44732 and 99982 correspond to the different seeds that have been used for the prediction. The network weights will be the same.

We choose the best model in the end based on model confidence which is a compound score: 0.2 * pTM + 0.8*ipTM.

_ptm.json actually contains the model confidence. I will fix this in the next few days and also write out the ipTMs.

**Comment by andreadiianni** [comment]
Many thanks for answering and for the implementation.
Now it is possible to retrieve all different parameters for the generated models.
