### ISSUE TITLE
Inter-subunit crosslinks 

### ISSUE THREAD

**Issue by jimfeng9705** [Rappsilber-Laboratory/AlphaLink2#24]
We have a homodimeric protein with chains A and B. How to define the sequence in the fasta file to be uploaded? Do we enter 1 sequence under >A, or two (identical) sequence with the same chain name?

Per the previous threads, there is no way to define inter-subunit XLs. Any progress in this?

As the AlphaLink 2 was trained with SDA, how trustworthy can we use the DSBU data? Any way to export the crosslink data from XiView for AlphaLink??

We appreciate your team doing this crosslink guided modeling for our community!

**Comment by lhatsk** [comment]
> We have a homodimeric protein with chains A and B. How to define the sequence in the fasta file to be uploaded? Do we enter 1 sequence under >A, or two (identical) sequence with the same chain name?

It depends very much on what you want to do. Atm, the system will recognize automatically that this is a homodimer. You can just put in the two sequences, e.g., >A ... >B ... If you specify your crosslinks as going from A to A, you will automatically have inter- and intra-subunit crosslinks. If you only want to have either inter or intra-subunits crosslinks it gets a little more tricky. I will soon push an update that doesn't automatically recognize the chains and then you can handle it however you want. 

> Per the previous threads, there is no way to define inter-subunit XLs. Any progress in this?

Do you mean ONLY inter-subunit crosslinks for homomers? This is possible but requires manual intervention.

Just as a summary: If you are ok with the ambiguity in the crosslinking data, just put in both chains separately and use a crosslinking dictionary/ file from chain A to chain A.


> As the AlphaLink 2 was trained with SDA, how trustworthy can we use the DSBU data?

How many links do you have? You can use the data but the performance will likely be worse.

> Any way to export the crosslink data from XiView for AlphaLink??

Not at the moment, but it's something we should be doing and I will talk to the XiView team.

**Comment by lhatsk** [comment]
[Xiview](https://github.com/Rappsilber-Laboratory/build-xiview/issues/106) now supports exporting crosslinks in the AlphaLink2 format. We change now the behavior for homomers. You will now need to specify if you want to include inter and intra-subunit crosslinks. E.g., for a homodimer >A ... >A ... we will internally use two sequences A,B and you need to specify intra-subunit crosslinks for A,A and inter-subunit crosslinks for A,B.

**Comment by jimfeng9705** [comment]
Great! Can you share sample csv and fasta files for such homodimeric protein (to be uploaded for AlphaLink2 & ColabFold)?

On Jun 14, 2024, at 05:07, lhatsk ***@***.***> wrote:

﻿
  [EXTERNAL]

Xiview<https://github.com/Rappsilber-Laboratory/build-xiview/issues/106> now supports exporting crosslinks in the AlphaLink2 format. We change now the behavior for homomers. You will now need to specify if you want to include inter and intra-subunit crosslinks. E.g., for a homodimer >A ... >A ... we will internally use two sequences A,B and you need to specify intra-subunit crosslinks for A,A and inter-subunit crosslinks for A,B.

**Comment by lhatsk** [comment]
Sorry, I don't have an example. But nothing changes in terms of usage. It's just that you need to define both inter- and intra-subunit crosslinks. You have these three options, assuming a homodimer the crosslink 1,50 is ambiguous:

Inter- and intra links:
1 A 50 B 0.1
1 A 50 A 0.1

Only intra-links:
1 A 50 A 0.1

Only inter-links:
1 A 50 B 0.1

**Comment by jimfeng9705** [comment]
How important is it to sort the residues (by their numbers) in the crosslinks CSV file?

On 6/22/2024 9:26 AM, lhatsk wrote:
  [EXTERNAL]

Sorry, I don't have an example. But nothing changes in terms of usage. It's just that you need to define both inter- and intra-subunit crosslinks. You have these three options, assuming a homodimer the crosslink 1,50 is ambiguous:

Inter- and intra links:
1 A 50 B 0.1
1 A 50 A 0.1

Only intra-links:
1 A 50 A 0.1

Only inter-links:
1 A 50 B 0.1

**Comment by lhatsk** [comment]
Order doesn't matter
