### ISSUE TITLE
chains.txt not found?

### ISSUE THREAD

**Issue by decortja** [Rappsilber-Laboratory/AlphaLink2#25]
Hello, and thanks for making AlphaLink2! Seems like a really exciting tool.

I am trying to use a single inter-chain crosslink in a heterodimer. I upload the fasta and crosslink files fine, but the notebook fails at the "AlphaLink prediction on GPU" step, with the following output regarding chains.txt being missing:

```
/usr/local/lib/python3.10/dist-packages/unifold/colab/data.py in load_feature_for_one_target(config, data_folder, seed, is_multimer, use_uniprot, symmetry_group)
    141     else:
    142         uniprot_msa_dir = data_folder
--> 143         sequence_ids = open(os.path.join(data_folder, "chains.txt")).readline().split()
    144 
    145     batch, _ = load_and_process(

FileNotFoundError: [Errno 2] No such file or directory: './prediction/5T35_1_dede7/chains.txt'
```

How can this be corrected?

**Comment by lhatsk** [comment]
Thanks for reporting this! I submitted a fix, should be working now.

**Comment by decortja** [comment]
Excellent, thank you! That cell is working. Now encountering a separate issue on the "prediction on GPU" cell, but I will close this issue and make a separate one for that.
