### ISSUE TITLE
distance_distribution, pae, plddt not in output directory

### ISSUE THREAD

**Issue by adahal258** [Rappsilber-Laboratory/AlphaLink2#29]
Does alphalink2 installed on local device creates  .svg files for distance_distribution, pae and plddt. I am not getting these files in my output directory.
Also, attached is the output I get, is it something with CUDA or openmm
![Capture](https://github.com/user-attachments/assets/e80500b9-c0c6-43da-b44f-201bc3e14754)

Thank You!

**Comment by lhatsk** [comment]
No, it's only part of ColabFold.

You can ignore the warning. We don't use jaxlib, it just comes with AlphaFold.

**Comment by jimfeng9705** [comment]
How can we obtain a jason file that contains plddt (scores)? We would like to use the scores file and the pdb to view the predictions, using, e.g., PAE Viewer?

**Comment by jimfeng9705** [comment]
Is it possible to generate the predicted LDDT images as we see on the colab site? See attached pictures.
![download](https://github.com/user-attachments/assets/c35b428b-a504-4b5b-9f5d-0e4e55511778)

**Comment by lhatsk** [comment]
The json files should be present in the output directory. I'm not sure if they have the same format as the AlphaFold score files though. The PAE viewer looks cool! You might need to change the format of the crosslinks if you want to show them.

You could generate the plots if you import colab_plot_confidence from unifold/colab/plot.py see https://github.com/Rappsilber-Laboratory/AlphaLink2/blob/main/unifold/colab/plot.py#L114

Maybe I will add it later.
